<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Attack</name>
   <tag></tag>
   <elementGuidId>ec73b1d6-9f2f-4f58-88af-cbf4d1081a86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrap']/div/ul[2]/li[2]/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>c429223d-cd42-47a0-a7bb-ff2da098a0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attack:</value>
      <webElementGuid>ac12fb92-6028-4c26-9448-2c8041cbf613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrap&quot;)/div[@class=&quot;mycardelectric&quot;]/ul[2]/li[2]/strong[1]</value>
      <webElementGuid>570c61c4-7f09-43f1-8f1a-436416885b79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/div/ul[2]/li[2]/strong</value>
      <webElementGuid>eb6f3b0e-619a-4440-924e-5868580d65bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP:'])[1]/following::strong[1]</value>
      <webElementGuid>32896294-ca96-487a-9de6-fd51b422d92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stats:'])[1]/following::strong[2]</value>
      <webElementGuid>0c451eaa-555d-4be4-9c4d-2fb760e3d226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Defense:'])[1]/preceding::strong[1]</value>
      <webElementGuid>0ad64ed4-e905-4962-bca0-f63a19a2dece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Attack:'])[1]/preceding::strong[2]</value>
      <webElementGuid>0a4610ad-c848-47b4-9b7c-3d516fcd618b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attack:']/parent::*</value>
      <webElementGuid>9bd0b164-7347-4323-8d78-843f5d391e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/strong</value>
      <webElementGuid>6a94fbe0-56f7-4b6c-ad0c-cbdc1abcd4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Attack:' or . = 'Attack:')]</value>
      <webElementGuid>aee743c0-a67f-4326-b4ec-6743c34a0232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
