<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back to community</name>
   <tag></tag>
   <elementGuidId>0b9acfe0-2d06-4ee4-8b97-aa43056d7207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrap']/a[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#content-wrap > a:nth-of-type(2) > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>faa70100-2b0c-4a89-8d1a-4a9b45e3fa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to community</value>
      <webElementGuid>a7499650-fb89-49c2-9b5c-34cf5f2667f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrap&quot;)/a[2]/button[1]</value>
      <webElementGuid>dca47295-85a1-4077-b661-a89a139a2789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/a[2]/button</value>
      <webElementGuid>c60473d9-d19d-4455-bb04-e4c964f3e692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to teams'])[1]/following::button[1]</value>
      <webElementGuid>50d58c85-cf9d-4055-9304-5438919eb773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='swords-dance'])[12]/following::button[2]</value>
      <webElementGuid>e9b68d58-1554-4ee5-9116-541ce8530403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created by Taj Smith 2024'])[1]/preceding::button[1]</value>
      <webElementGuid>3fa2cf6c-3a2a-4aff-b635-4ee5fba04cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to community']/parent::*</value>
      <webElementGuid>2bb8b6f9-b59b-4c59-9a10-592fbe015808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/button</value>
      <webElementGuid>fe88787b-063f-4177-b643-cc4718886fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Back to community' or . = 'Back to community')]</value>
      <webElementGuid>580191af-1f31-4fed-bf53-f4e6be2814a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
