<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbutttacklebody-slamtake-downdoub_18edfb_1_2</name>
   <tag></tag>
   <elementGuidId>a0f6387f-04d5-4968-9244-f36debc438f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move4_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move4_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d87645f-3bd5-4ef7-9f7c-56fe0dac1e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move4_3</value>
      <webElementGuid>98dc8c60-e4e6-4c62-af6a-5ec56a81b67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move4_3</value>
      <webElementGuid>15c71d8c-b69d-468e-a0ba-85b0580cca9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press</value>
      <webElementGuid>1252d221-ab56-41cd-9618-d5a246fae808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move4_3&quot;)</value>
      <webElementGuid>f4f00925-7bea-4e09-9298-44761c49b628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move4_3']</value>
      <webElementGuid>943c2376-c30d-47fd-8ff9-fd9c7bb0b3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[25]/select</value>
      <webElementGuid>2cb5d8a4-2a45-4531-a603-054854117f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[4]/following::select[1]</value>
      <webElementGuid>979d4514-1e5d-4885-b917-7a9f51cab353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[4]/following::select[2]</value>
      <webElementGuid>4bc06b4c-59a4-43b0-a5b0-b00221611205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[4]/preceding::select[1]</value>
      <webElementGuid>770d0070-cdec-4bf5-99bd-4d29070a6bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 5'])[1]/preceding::select[2]</value>
      <webElementGuid>f9cf9308-37f1-4a95-8d00-5dcc6b7c7082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/select</value>
      <webElementGuid>b219c449-d9c7-4623-b2c8-35bcbe3a9d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move4_3' and @id = 'id_move4_3' and (text() = 'headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press' or . = 'headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press')]</value>
      <webElementGuid>8d575477-faf1-44d1-a8ce-57130696f609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
