<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_blazespeed-boost</name>
   <tag></tag>
   <elementGuidId>691ac85b-241a-4398-8ae5-1c6e475ee39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_ability6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_ability6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e55b2d76-60fc-4e64-b67e-6acbc327aa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ability6</value>
      <webElementGuid>bc1a620c-4fc6-4c2d-8e06-b1330ab8843c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_ability6</value>
      <webElementGuid>e3b91883-deef-4f49-a4a3-3a121751ff55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>blazespeed-boost</value>
      <webElementGuid>385e5b03-5639-4317-a0bf-a967455bb57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_ability6&quot;)</value>
      <webElementGuid>9e412137-8453-45be-9a82-4fbad59f6a41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_ability6']</value>
      <webElementGuid>bd798c4e-5226-465c-acd7-00979c5a7370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[34]/select</value>
      <webElementGuid>0d8a5fb5-d4c4-4fea-bccb-c3e7a010bd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[6]/following::select[1]</value>
      <webElementGuid>d52a4131-59af-4cb9-96df-ee284befb7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 6'])[1]/following::select[2]</value>
      <webElementGuid>e3df969e-1428-4b16-a35d-ccc4f1163ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[6]/preceding::select[1]</value>
      <webElementGuid>cc73bb8f-b867-451b-a95b-3f67cd135668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[6]/preceding::select[2]</value>
      <webElementGuid>8dac54ae-80be-45b8-97f6-23e8535a9951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[34]/select</value>
      <webElementGuid>47966a7b-5b7d-46c6-918b-c9f302b675ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ability6' and @id = 'id_ability6' and (text() = 'blazespeed-boost' or . = 'blazespeed-boost')]</value>
      <webElementGuid>03f6228c-d0a7-41e2-a361-fe76e4f6076f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
