<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_unnerverivalrymold-breaker</name>
   <tag></tag>
   <elementGuidId>1b09cfce-cd52-40f8-8582-0969c7cc4655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_ability2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_ability2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41fcfb71-396b-47e8-8e25-fec2ad873749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ability2</value>
      <webElementGuid>72b49a1b-8817-4ef3-a4a1-bd6176ff66e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_ability2</value>
      <webElementGuid>736e0a22-ee03-4652-8b41-b549f0e5df97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>unnerverivalrymold-breaker</value>
      <webElementGuid>8e2e6a8a-bf53-4028-b4e0-801b5d326f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_ability2&quot;)</value>
      <webElementGuid>3bdf9387-05a1-4a3e-8901-0653944d2e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_ability2']</value>
      <webElementGuid>aa21a4c1-63aa-4573-bcd0-e8f811158429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[10]/select</value>
      <webElementGuid>1bc96f7e-fe0e-4b46-b9be-f33dc8fa452e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[2]/following::select[1]</value>
      <webElementGuid>e85ef4ea-3f66-4f6a-bc77-07409269294f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 2'])[1]/following::select[2]</value>
      <webElementGuid>b438cbca-3e5e-482d-8f36-23bf84fba086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[2]/preceding::select[1]</value>
      <webElementGuid>d0a4c793-b79b-4dad-87aa-8215bf3df524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[2]/preceding::select[2]</value>
      <webElementGuid>227da950-adcd-4a8b-880c-c04252523a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/select</value>
      <webElementGuid>018e3960-9758-4b35-9635-7b21c17efe38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ability2' and @id = 'id_ability2' and (text() = 'unnerverivalrymold-breaker' or . = 'unnerverivalrymold-breaker')]</value>
      <webElementGuid>586cc3e1-4a66-41f5-b568-8d127bf0f991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
