<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-dancecutheadbuttbody-slamtake_ab05fc_1_2</name>
   <tag></tag>
   <elementGuidId>ea96ba33-bb53-481f-b9ae-49a0ff2e8bab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move6_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move6_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a10c359e-e684-48ed-8020-64d385a4a7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move6_3</value>
      <webElementGuid>f15c737a-f747-40c5-92f7-ce6c14ff795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move6_3</value>
      <webElementGuid>43c15e4e-9c3c-4f29-8b68-7668ed45db7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut</value>
      <webElementGuid>bb5468e6-76f9-47aa-994e-9406be335531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move6_3&quot;)</value>
      <webElementGuid>01a1f349-82b8-4f5d-a2b4-7344a2ef31d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move6_3']</value>
      <webElementGuid>881c4a11-5d12-4736-9ad9-ec0cd5d7a616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[37]/select</value>
      <webElementGuid>5ae9c30b-cd23-4160-b513-85a4d531dfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[6]/following::select[1]</value>
      <webElementGuid>c14def84-acab-4672-83f4-5dc27a951c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[6]/following::select[2]</value>
      <webElementGuid>3175d533-0b10-4345-ba36-b8bfab9751d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[6]/preceding::select[1]</value>
      <webElementGuid>55362dab-f668-42d9-8e79-4adb41f0589d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[2]</value>
      <webElementGuid>bc22c725-e122-42ff-b67c-1fbe186b5a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[37]/select</value>
      <webElementGuid>05da06d1-be2d-419b-bb43-d64e0696a3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move6_3' and @id = 'id_move6_3' and (text() = 'swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut' or . = 'swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut')]</value>
      <webElementGuid>3c78a197-45b0-4560-afd9-5e98c421b537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
