<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-dancecutheadbuttbody-slamtake_ab05fc_1</name>
   <tag></tag>
   <elementGuidId>211316e3-6fb6-43f8-b1fe-382c611c8a5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move6_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move6_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>26ed17eb-bb30-4417-9636-12b7cc51b07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move6_2</value>
      <webElementGuid>dcebe9dc-eae3-40c5-ac51-dc886b962285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move6_2</value>
      <webElementGuid>82cba8e2-d815-4cf0-9efd-c96ba0b7913f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut</value>
      <webElementGuid>1b748366-e332-4f8d-a880-9b17c67d0c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move6_2&quot;)</value>
      <webElementGuid>a6d802b9-8479-4d93-8057-cc0e95ed9977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move6_2']</value>
      <webElementGuid>38c08603-4a56-4474-83aa-9d4e4e301f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[36]/select</value>
      <webElementGuid>1e3b3a12-29cd-4231-8bb2-b7abd4d6c9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[6]/following::select[1]</value>
      <webElementGuid>5167bbc8-b61b-4484-bbdf-c9f8313e5f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[6]/following::select[2]</value>
      <webElementGuid>f1d08856-0600-46c5-b349-1a2b95a4a0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[6]/preceding::select[1]</value>
      <webElementGuid>8c22f993-0430-42f2-932f-c0ec88a2d354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[6]/preceding::select[2]</value>
      <webElementGuid>35f7cd7f-ba44-4127-9652-260abb3713bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[36]/select</value>
      <webElementGuid>e10ab879-0165-4982-9583-a45bc460f96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move6_2' and @id = 'id_move6_2' and (text() = 'swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut' or . = 'swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut')]</value>
      <webElementGuid>84242e23-926d-4b68-ade4-42d776ff85fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
