<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-dancecutbody-slamtake-downdou_7825e0_1_2</name>
   <tag></tag>
   <elementGuidId>52eae084-8ffb-4612-a2bc-0569175c1009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move2_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move2_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>18f75a81-57e8-4e32-b2c2-0039701de999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move2_3</value>
      <webElementGuid>8cbc8a17-587f-4dcf-9a5c-32adad4bc445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move2_3</value>
      <webElementGuid>3c7ce13b-6f36-4c61-b305-e388473bc559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor</value>
      <webElementGuid>4b3ef0c5-9627-4115-8de8-0c8695f28db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move2_3&quot;)</value>
      <webElementGuid>08b80a5e-871c-43f4-bf84-845c20e338ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move2_3']</value>
      <webElementGuid>71f1c1da-8858-4792-b962-846f50998b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[13]/select</value>
      <webElementGuid>9c889c97-3025-4216-b386-02d20b98e606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[2]/following::select[1]</value>
      <webElementGuid>4df4aeac-c123-48fd-bb27-dbe8c5265f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[2]/following::select[2]</value>
      <webElementGuid>7cacc00f-67b2-4f62-95c2-b9afe5096d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[2]/preceding::select[1]</value>
      <webElementGuid>1fd5c1a4-8dd1-40f3-887d-d2bd02ff5d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 3'])[1]/preceding::select[2]</value>
      <webElementGuid>90309e7a-d90c-422f-96b6-398f7524389e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/select</value>
      <webElementGuid>1bd1019e-df81-452a-a409-3ecaa071d9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move2_3' and @id = 'id_move2_3' and (text() = 'swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor' or . = 'swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor')]</value>
      <webElementGuid>20e2bf5f-d7d1-4098-ac5f-f6fcaa00dfe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
