<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbuttbody-slamtake-downdouble-edg_ccc634_1</name>
   <tag></tag>
   <elementGuidId>0fbe691f-82d2-49da-9af2-ebe7eda5bed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move1_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move1_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c1b28a69-79e3-4648-9883-4e20cc4f23cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move1_2</value>
      <webElementGuid>3ee7c2f9-b9ea-4cbd-8255-bd80be130ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move1_2</value>
      <webElementGuid>eb130fd8-3e65-483b-99d7-efbd99b18257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam</value>
      <webElementGuid>b7afc476-52da-4d9e-a644-df1a5d47716f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move1_2&quot;)</value>
      <webElementGuid>a9f1a737-596b-4d19-836a-f5bd86e49329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move1_2']</value>
      <webElementGuid>7e8dd31c-aab8-4024-a81b-b633a547c90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[6]/select</value>
      <webElementGuid>b0c74519-a7c5-4fdb-b24e-40ca05ccda24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[1]/following::select[1]</value>
      <webElementGuid>ca3289ef-3e12-4f6a-95c7-e203f48c2387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[1]/following::select[2]</value>
      <webElementGuid>5116581b-c614-4936-abbd-4d4971327a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[1]/preceding::select[1]</value>
      <webElementGuid>e48ab9f3-0a5d-4489-9be6-5e785930197b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[1]/preceding::select[2]</value>
      <webElementGuid>fc433da8-0fc5-46b8-b5f8-a4584b6c87fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>66bca169-3f4d-425f-80e7-28c995ee405f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move1_2' and @id = 'id_move1_2' and (text() = 'headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam' or . = 'headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam')]</value>
      <webElementGuid>ff2d8b3d-bd49-4552-812e-de0b89651054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
