<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-dancecutbody-slamtake-downdou_7825e0</name>
   <tag></tag>
   <elementGuidId>134f63b7-7fb5-42d7-b580-6e485e716294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move2_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move2_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>551dd0cc-729a-4dd5-bbbb-be9647ba1fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move2_1</value>
      <webElementGuid>c51f068e-a5fc-4979-820d-6a40950371e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move2_1</value>
      <webElementGuid>321008a5-8b33-4d8c-9733-808679d06cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor</value>
      <webElementGuid>af4d6d80-aab2-4f21-83a5-c30235a15291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move2_1&quot;)</value>
      <webElementGuid>7bc49cae-3520-4a10-a9f3-aad916d85261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move2_1']</value>
      <webElementGuid>40aa72b1-5e51-4ca3-89c1-8c47c78d1e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[11]/select</value>
      <webElementGuid>ef032db3-0d54-4f25-84c7-4f18a3e6709e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[2]/following::select[1]</value>
      <webElementGuid>dddf0a79-63c9-4d04-8aa1-47717099f07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[2]/following::select[2]</value>
      <webElementGuid>d90a61b0-a656-4a47-863c-1000796fc4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[2]/preceding::select[1]</value>
      <webElementGuid>da3b2b97-ce7c-4002-a7ed-f4446131ab64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[2]/preceding::select[2]</value>
      <webElementGuid>3f03fb8b-0755-4c55-b233-2ec876bd62e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/select</value>
      <webElementGuid>5f84dd3c-7b27-46d4-8760-6e3edf88fed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move2_1' and @id = 'id_move2_1' and (text() = 'swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor' or . = 'swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor')]</value>
      <webElementGuid>7a5e5785-6c30-4da4-8d2c-d94c9933632b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
