<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbutttacklebody-slamtake-downdoub_18edfb_1_2_3</name>
   <tag></tag>
   <elementGuidId>dd1917d0-a38a-411c-932e-905f3c53d20f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move4_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move4_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cbb0935b-aba7-4757-87c9-f18afbd7d26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move4_4</value>
      <webElementGuid>ee167606-e274-49aa-ad12-ab3bf46698fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move4_4</value>
      <webElementGuid>84e0753d-064b-4ff1-a746-1602bbf73ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press</value>
      <webElementGuid>621188e3-fbb1-4518-a459-a7faa4502dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move4_4&quot;)</value>
      <webElementGuid>0f5fd405-4269-4c4e-a836-18286b4114cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move4_4']</value>
      <webElementGuid>8cc78753-03cd-4ccb-9b16-622c48a24548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[26]/select</value>
      <webElementGuid>50bd220d-406f-4d39-9e43-c0d435443916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[4]/following::select[1]</value>
      <webElementGuid>26e98447-2246-4be6-9bce-d1e07a874b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[4]/following::select[2]</value>
      <webElementGuid>83edb688-d13f-4a77-9305-549b98564b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 5'])[1]/preceding::select[1]</value>
      <webElementGuid>0913b994-29d2-4ed1-a97d-c5df749df65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[5]/preceding::select[2]</value>
      <webElementGuid>1f73679a-3b3f-45ef-b9e2-6b70eec038f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/select</value>
      <webElementGuid>52e0ffda-c1f6-4467-b454-fd4aa2212059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move4_4' and @id = 'id_move4_4' and (text() = 'headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press' or . = 'headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press')]</value>
      <webElementGuid>148243ef-4be9-46af-a27c-5136f1f18ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
