<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbuttbody-slamtake-downdouble-edg_4ff3fc_1_2_3</name>
   <tag></tag>
   <elementGuidId>87cd87bb-7082-4045-8017-47ba6c914a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move5_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move5_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c736c599-c882-4e08-94f9-1ea0cd128726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move5_4</value>
      <webElementGuid>36cde139-2573-4d11-9dca-6cbb24c1fc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move5_4</value>
      <webElementGuid>b81bf0d2-9af1-4440-86f5-ee2b9623491e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor</value>
      <webElementGuid>1fc85c33-3be2-4c01-95b2-26339b0fa563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move5_4&quot;)</value>
      <webElementGuid>f910ca35-5089-4183-b96a-aee2cf6ff8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move5_4']</value>
      <webElementGuid>a69815ba-bdf5-4531-a3f9-c6ac5d9b883c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[32]/select</value>
      <webElementGuid>7215646b-9871-41d5-87d1-eb435cbf5019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[5]/following::select[1]</value>
      <webElementGuid>ddee90df-812d-4702-bf4c-82310fe9fdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[5]/following::select[2]</value>
      <webElementGuid>6468f263-beee-4f1a-b54e-6016f772e5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 6'])[1]/preceding::select[1]</value>
      <webElementGuid>91ffd070-c617-4649-b9a7-1a2222396a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[6]/preceding::select[2]</value>
      <webElementGuid>a124c4ee-3286-4e4b-b058-ebd22ec5c4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]/select</value>
      <webElementGuid>7ea70d71-b9b3-4eff-8e6f-22ea50310a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move5_4' and @id = 'id_move5_4' and (text() = 'headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor' or . = 'headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor')]</value>
      <webElementGuid>d7c6ac23-7fdc-4442-a0e8-49772e3d4b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
