<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-danceheadbuttbody-slamtake-do_60a0ca_1</name>
   <tag></tag>
   <elementGuidId>fcfef9c3-43a6-4a2d-98d2-c42ade70edb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move3_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move3_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>771c80cb-3e49-4c23-b619-8297cb1e05ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move3_3</value>
      <webElementGuid>d83788cf-9ba7-45fa-8e45-ab636f4f94be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move3_3</value>
      <webElementGuid>78657601-423e-45b4-af09-c0b5bf36b067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm</value>
      <webElementGuid>cfc2be3d-e824-46de-9901-29de59ddabb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move3_3&quot;)</value>
      <webElementGuid>efc5ad33-5455-4022-b875-96676ed094da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move3_3']</value>
      <webElementGuid>53f14d67-4d95-4a63-bf89-fc11001e241b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[19]/select</value>
      <webElementGuid>61b67355-b1da-4bd7-9dbb-317dd9f59e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[3]/following::select[1]</value>
      <webElementGuid>13b4f6ea-35cb-49ad-a675-2ef5deacc426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[3]/following::select[2]</value>
      <webElementGuid>f5984950-8d46-42df-a24f-24a14b69ae0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[3]/preceding::select[1]</value>
      <webElementGuid>56e2f3fd-9760-477d-b8c6-f667dd300ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 4'])[1]/preceding::select[2]</value>
      <webElementGuid>8b3c18dc-f719-476a-8b25-e371edfcf782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/select</value>
      <webElementGuid>4cec7c38-4c09-4789-b5bf-7002ffda2530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move3_3' and @id = 'id_move3_3' and (text() = 'swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm' or . = 'swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm')]</value>
      <webElementGuid>0d034944-6930-4b2e-85f0-20ac3d1d032e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
