<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbuttbody-slamtake-downdouble-edg_ccc634_1_2</name>
   <tag></tag>
   <elementGuidId>dada4155-5829-4066-a249-772cfe2e95fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move1_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move1_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ccc6441-605f-46c3-b920-0f0d7e1fb601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move1_3</value>
      <webElementGuid>82aaf914-d711-44d8-bac6-259172876b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move1_3</value>
      <webElementGuid>f3c8a53c-1aed-4a47-a236-75d47906ea5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam</value>
      <webElementGuid>f8456799-c190-4efc-8453-c50406a80aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move1_3&quot;)</value>
      <webElementGuid>e23b722d-e560-4f74-8321-a7a8f5f6369b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move1_3']</value>
      <webElementGuid>ccb56334-f049-438e-86c2-008a06a803da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[7]/select</value>
      <webElementGuid>b2fd2bd3-0a32-4082-8af5-06b9b615a51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[1]/following::select[1]</value>
      <webElementGuid>a0ad1181-5ab0-4985-9dd1-00e7a5adcf4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[1]/following::select[2]</value>
      <webElementGuid>164a54e8-2c2f-4edb-b0e9-01df29f5f9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[1]/preceding::select[1]</value>
      <webElementGuid>965598d8-297c-4e34-b015-83041156c90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 2'])[1]/preceding::select[2]</value>
      <webElementGuid>d91d8603-5d4a-4c81-ac46-51ae31473930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>6cc519c6-75ce-4a92-8d85-63e46eb3e5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move1_3' and @id = 'id_move1_3' and (text() = 'headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam' or . = 'headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam')]</value>
      <webElementGuid>b57f778d-11e3-4f96-8252-1191ed536e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
