<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-dancecutbody-slamtake-downdou_7825e0_1_2_3</name>
   <tag></tag>
   <elementGuidId>fadc1ffb-5919-43ab-a915-426d266b8211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move2_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move2_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9a85205-1419-4632-97db-000c0df16e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move2_4</value>
      <webElementGuid>76f61b36-b781-4698-9fc2-2b75afb73c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move2_4</value>
      <webElementGuid>5c9b5979-2f65-4a55-90cc-96b9becb6dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor</value>
      <webElementGuid>01b87fe2-f1f8-4c52-a7f3-740edcce3fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move2_4&quot;)</value>
      <webElementGuid>e13c0de6-8774-4786-a159-c93a64e5eece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move2_4']</value>
      <webElementGuid>4717a91c-e937-44e7-9e5e-e5b72df22706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[14]/select</value>
      <webElementGuid>131be5e1-4969-4434-ac31-81fec4574c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[2]/following::select[1]</value>
      <webElementGuid>21b72f28-b70d-4cad-9cd0-f3b82e5b2ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[2]/following::select[2]</value>
      <webElementGuid>6b752d6c-ddb2-4f7d-a195-aca04c254e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 3'])[1]/preceding::select[1]</value>
      <webElementGuid>0a65bfb9-b5fb-4350-b96e-a32e24b36d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[3]/preceding::select[2]</value>
      <webElementGuid>21ea432b-6656-49c3-b7bc-bccaf766b5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/select</value>
      <webElementGuid>66571ec7-e982-4695-a760-454e67894c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move2_4' and @id = 'id_move2_4' and (text() = 'swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor' or . = 'swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor')]</value>
      <webElementGuid>5c24e51f-a380-49e7-b510-3a96acec6250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
