<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbuttbody-slamtake-downdouble-edg_ccc634</name>
   <tag></tag>
   <elementGuidId>131711bd-3826-434c-b90f-6f670c51529d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move1_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move1_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ef3a1cf-d0c1-4b34-8785-f1305b5b85c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move1_1</value>
      <webElementGuid>24febfc3-0de2-47d6-bf0a-2eda41bd93d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move1_1</value>
      <webElementGuid>8984cf7e-eca8-4764-a961-95eff8433a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam</value>
      <webElementGuid>824efff2-effd-4b76-a21d-8f6fc1af9656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move1_1&quot;)</value>
      <webElementGuid>8135aa8a-dc92-4189-8880-e5eba5620755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move1_1']</value>
      <webElementGuid>c97e94ee-db50-410f-9fa3-dc9b7dbbb371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[5]/select</value>
      <webElementGuid>5359f134-0078-47a5-a50a-538b3a1ef3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[1]/following::select[1]</value>
      <webElementGuid>8a137f21-8b31-4bdc-b21e-3440f720bbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[1]/following::select[2]</value>
      <webElementGuid>7af16433-c78a-417b-853c-7ae81eeecc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[1]/preceding::select[1]</value>
      <webElementGuid>522b631c-8194-4d80-8c98-6fcf2147b609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[1]/preceding::select[2]</value>
      <webElementGuid>51fad750-79a7-4d70-a9e6-782d4c4c0892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>18cfa8a3-b62f-4337-a72c-06d9f0aa0c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move1_1' and @id = 'id_move1_1' and (text() = 'headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam' or . = 'headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam')]</value>
      <webElementGuid>a23e2d55-873a-4a3a-94a2-e1b59c8d3b7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
