<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-dancecutbody-slamtake-downdou_7825e0_1</name>
   <tag></tag>
   <elementGuidId>3cbad007-1aa7-4f08-81ea-fee2122c3c4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move2_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move2_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d6d30442-5367-4324-8e65-044ba60caef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move2_2</value>
      <webElementGuid>d0949f3e-0873-41a9-abe5-0fe27cbefb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move2_2</value>
      <webElementGuid>84cb4f70-c5ac-48a1-8e2f-9743c5005baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor</value>
      <webElementGuid>92e5e361-60dd-49e1-9f69-77d962b53e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move2_2&quot;)</value>
      <webElementGuid>4ccefec2-e63e-4f90-9ace-4a57c68b64e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move2_2']</value>
      <webElementGuid>318cd12c-9549-4307-b499-c9a0cf0a1ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[12]/select</value>
      <webElementGuid>1c1102bf-9a08-444d-b3cd-a5c8df914b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[2]/following::select[1]</value>
      <webElementGuid>51dfd38a-c2fa-4802-80ba-518d2888917d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[2]/following::select[2]</value>
      <webElementGuid>1562642c-7e5b-42b0-9a94-4057f30d260f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[2]/preceding::select[1]</value>
      <webElementGuid>ed1568f2-dc7f-4155-81a2-e75bd9392904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[2]/preceding::select[2]</value>
      <webElementGuid>56a78d44-11d6-4d44-8988-97f796a984a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/select</value>
      <webElementGuid>98cc1691-8e72-4675-b056-ee3ce05cb407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move2_2' and @id = 'id_move2_2' and (text() = 'swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor' or . = 'swords-dancecutbody-slamtake-downdouble-edgestrengthtoxicdouble-teamrestsubstitutesnoreprotectoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadesecret-powergrass-knotroundconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactbulldozestomping-tantrumscratchleerbitedragon-ragedigswiftrock-slideslashiron-tailcrunchbrick-breakrock-tombaerial-acedragon-clawdragon-danceflingdragon-pulsefocus-blastshadow-clawhone-clawsincineratedragon-tailbreaking-swipebrutal-swingscale-shotdragon-cheersurfrain-danceaqua-tailfocus-energyendeavorpaybackassurancex-scissorlaser-focusreversaltauntshock-wavesnarllow-kicksuperpowerlow-sweepclose-combatdual-chopiron-headpsycho-cutguillotinedraco-meteor')]</value>
      <webElementGuid>d8195d14-5534-4e08-8e4f-808c34fcfa42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
