<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_inner-focusjustifiedsteadfast</name>
   <tag></tag>
   <elementGuidId>a72dd9be-8747-4dcc-9d63-db9546ea9b56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_ability3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_ability3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9cafadd-a72f-48de-88f1-3c834cfd2dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ability3</value>
      <webElementGuid>09b47d1b-9e33-45f0-8702-26c5b3079c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_ability3</value>
      <webElementGuid>0b1ce320-2412-4c90-bbf6-d1404c5f10cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>inner-focusjustifiedsteadfast</value>
      <webElementGuid>67067f33-05a2-402d-82d3-1089b000e774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_ability3&quot;)</value>
      <webElementGuid>8640a64c-5455-4466-862e-7599cef07cc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_ability3']</value>
      <webElementGuid>7b65ea50-896e-4d61-b399-636a82c0cb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[16]/select</value>
      <webElementGuid>7a325ce5-ba16-49cc-83ad-8531460c691c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[3]/following::select[1]</value>
      <webElementGuid>ce1b7baf-8caa-4bae-a121-e7671c3683a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 3'])[1]/following::select[2]</value>
      <webElementGuid>8639c3dc-cdd5-457c-80d7-0cabfe5aa361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[3]/preceding::select[1]</value>
      <webElementGuid>f0386648-6ceb-4175-b737-28635a428629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[3]/preceding::select[2]</value>
      <webElementGuid>74c17fee-4001-46c4-9da7-d61a952e1d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/select</value>
      <webElementGuid>ec98bf88-90e7-4ee3-bb19-34ba9c6fdd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ability3' and @id = 'id_ability3' and (text() = 'inner-focusjustifiedsteadfast' or . = 'inner-focusjustifiedsteadfast')]</value>
      <webElementGuid>529d38aa-eb4b-496c-809b-d01fb0dab36d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
