<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_sniperdampswift-swim</name>
   <tag></tag>
   <elementGuidId>ed1f4c45-e6ee-42c1-af0a-9ad3508e47f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_ability5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_ability5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0dc20a1e-242f-4094-bbbf-191b00866502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ability5</value>
      <webElementGuid>adcf565b-d746-41f0-8e87-59647bb390b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_ability5</value>
      <webElementGuid>65d4602a-439a-44d0-96eb-c79b27e9ae20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sniperdampswift-swim</value>
      <webElementGuid>e1067877-0f7d-43b2-b274-6d678dfdda0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_ability5&quot;)</value>
      <webElementGuid>c84d3c9a-3efc-4dc4-af4d-7e0e7fa223e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_ability5']</value>
      <webElementGuid>e4a83ed8-105a-4c2b-8ef5-d5c8941cd5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[28]/select</value>
      <webElementGuid>51ed89f8-fec4-44d3-98b9-ed5dd2bf1ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[5]/following::select[1]</value>
      <webElementGuid>5a68f128-4159-41a1-a5fd-0bbe57eb0dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 5'])[1]/following::select[2]</value>
      <webElementGuid>d920804c-d6e4-49a6-8573-92e026d4139e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[5]/preceding::select[1]</value>
      <webElementGuid>00a078e8-7a65-4975-b941-e496d960cd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[5]/preceding::select[2]</value>
      <webElementGuid>3a460df7-30de-488f-98c9-7fabb8c76b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/select</value>
      <webElementGuid>4cef9e70-926a-4e84-bda5-64bf7e9b984c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ability5' and @id = 'id_ability5' and (text() = 'sniperdampswift-swim' or . = 'sniperdampswift-swim')]</value>
      <webElementGuid>e60789c5-5811-435e-bced-9c7e4593ec1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
