<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-dancecutheadbuttbody-slamtake_ab05fc</name>
   <tag></tag>
   <elementGuidId>3219169d-c7a3-434d-b021-7d0f692aca96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move6_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move6_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b50c209a-084e-4e95-9811-2320698bc5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move6_1</value>
      <webElementGuid>60c2f33a-5320-4ffb-80c4-51a6c2f571de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move6_1</value>
      <webElementGuid>1f30b81c-d8c5-4da8-973a-466dcef3e42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut</value>
      <webElementGuid>34521d5b-5a8b-46fe-8278-6040b4c2a4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move6_1&quot;)</value>
      <webElementGuid>e6308787-21b8-42ef-9571-187a702d9bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move6_1']</value>
      <webElementGuid>93f92400-fb20-4b7c-b9af-bc9bf8789fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[35]/select</value>
      <webElementGuid>84ee39e5-8788-4327-864c-fcf64cac6769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[6]/following::select[1]</value>
      <webElementGuid>d50842a5-f499-4ffd-9087-b34c0ef55c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[6]/following::select[2]</value>
      <webElementGuid>3d336a25-f5e0-4030-9024-6bfbd47a9f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[6]/preceding::select[1]</value>
      <webElementGuid>863e1716-1a4d-44d2-bf4f-5c622de5eb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[6]/preceding::select[2]</value>
      <webElementGuid>1428508b-a313-4260-9a46-2539521aca6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[35]/select</value>
      <webElementGuid>d20719c2-901e-4500-9163-18567a3fe69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move6_1' and @id = 'id_move6_1' and (text() = 'swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut' or . = 'swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut')]</value>
      <webElementGuid>94942406-4ea3-48fe-88de-04e242f346af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
