<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbuttbody-slamtake-downdouble-edg_ccc634_1_2_3</name>
   <tag></tag>
   <elementGuidId>3eb15251-32c8-4adc-b5a2-ea32deb9a52f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move1_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move1_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2fcfbd10-a8a8-48db-bea8-c9cc1fd985f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move1_4</value>
      <webElementGuid>c332eca8-f469-4e2d-ae99-5b9afaaef8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move1_4</value>
      <webElementGuid>5fdd75c0-421c-47da-a416-3be12f5ddaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam</value>
      <webElementGuid>2bdd41bb-e3ee-431e-bb1b-8d20a16376a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move1_4&quot;)</value>
      <webElementGuid>9b387657-32e0-4d7b-84b5-86db39537888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move1_4']</value>
      <webElementGuid>b0b489b9-e9c3-437f-8978-d0ccf520fbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[8]/select</value>
      <webElementGuid>a810b18f-441b-466c-b230-1160b81a7ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[1]/following::select[1]</value>
      <webElementGuid>a59bfafa-7e37-49db-9869-739db664d2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[1]/following::select[2]</value>
      <webElementGuid>4b089abf-2aad-4be0-b9f9-53b0a6245dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 2'])[1]/preceding::select[1]</value>
      <webElementGuid>11a63f6e-5177-41b1-91c6-0d92252100a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[2]/preceding::select[2]</value>
      <webElementGuid>a75a7e24-d318-4310-a861-412eca8ea9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>a337d304-2850-4969-a828-815f67c7985a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move1_4' and @id = 'id_move1_4' and (text() = 'headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam' or . = 'headbuttbody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamlight-screenbideskull-bashrestsubstitutesnorecurseprotectmud-slapendureswaggerattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundwork-upconfidehyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozestomping-tantrummega-punchfire-punchthunder-punchmega-kickleerflamethrowersubmissioncounterseismic-tossdigfire-blastrock-slidedynamic-punchfocus-punchbrick-breakrock-tombflingfocus-blastincineratepower-up-punchfissureice-punchforesightrain-dancesmack-downthieffocus-energypaybackassurancethroat-chopdetectreversalrevengeretaliateencorelow-kickstone-edgehigh-horsepowersuperpowerrock-blastmetronomerole-playwake-up-slapcross-poisonwide-guardcross-chopvacuum-wavelow-sweepkarate-chopbulk-upclose-combatdual-chopdarkest-lariatcoachingvital-throwheavy-slam')]</value>
      <webElementGuid>2232332b-9d3f-407a-b327-7f8ce2f05a57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
