<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbutttacklebody-slamtake-downdoub_18edfb</name>
   <tag></tag>
   <elementGuidId>956506f8-7a12-4fe2-9c6f-14191777f25a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move4_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move4_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a9e2b3ca-faf9-4013-958c-247f89057818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move4_1</value>
      <webElementGuid>9f87b944-6646-423c-88cc-1e7e56a7504d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move4_1</value>
      <webElementGuid>5a162ba8-1841-4105-9f35-ce3869e30a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press</value>
      <webElementGuid>24b51e3f-1383-4fdf-acbe-22787e28e7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move4_1&quot;)</value>
      <webElementGuid>95b7b349-a43b-478b-9de1-64cca1554ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move4_1']</value>
      <webElementGuid>f4405f75-4b78-4707-afa7-ed135a25403c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[23]/select</value>
      <webElementGuid>5bbc3c25-cf75-47e0-b4c7-9bb9a5043b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[4]/following::select[1]</value>
      <webElementGuid>167d3df4-cc32-4173-bc86-ff7848f20a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[4]/following::select[2]</value>
      <webElementGuid>7b456903-583e-49c3-aad6-3ff6e02e3913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[4]/preceding::select[1]</value>
      <webElementGuid>fdbf138b-bfe4-43f7-970b-9ad6665a6a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[4]/preceding::select[2]</value>
      <webElementGuid>b7d1b7da-6ae3-4b64-b183-740f7393d667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/select</value>
      <webElementGuid>e59aa426-7602-4c87-ac7f-e6773f610230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move4_1' and @id = 'id_move4_1' and (text() = 'headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press' or . = 'headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press')]</value>
      <webElementGuid>c53f7adf-add4-402b-8804-1df534904193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
