<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbuttbody-slamtake-downdouble-edg_4ff3fc_1_2</name>
   <tag></tag>
   <elementGuidId>de2244c0-6bb8-44a7-8742-66b78d8bfd59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move5_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move5_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>207ee408-96e5-4ad7-9f53-d09cbbecb938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move5_3</value>
      <webElementGuid>2e6bade0-7833-4d7a-8157-e1614eab3cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move5_3</value>
      <webElementGuid>91a22fae-e7f1-4792-b2f7-5edc86a058f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor</value>
      <webElementGuid>3f9f8cd7-c6be-498a-af8f-96aafd05dd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move5_3&quot;)</value>
      <webElementGuid>275545e6-ee8a-4c56-b25f-061b3012543c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move5_3']</value>
      <webElementGuid>5aa996da-4e9d-447a-8daf-f03dd1f1ce05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[31]/select</value>
      <webElementGuid>4e802671-abd5-4223-8088-1e9a0f8992ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[5]/following::select[1]</value>
      <webElementGuid>ca3875cc-4140-445d-a6ea-7b687efd9eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[5]/following::select[2]</value>
      <webElementGuid>f8d4a5c5-2c48-4248-a971-f7d5f68da78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[5]/preceding::select[1]</value>
      <webElementGuid>713e08da-647c-43b9-9aba-e2895b4e8141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 6'])[1]/preceding::select[2]</value>
      <webElementGuid>4ea1add2-8f31-49d4-bbac-b94c7d874bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/select</value>
      <webElementGuid>d620ef2b-a69c-44d6-93c3-f20d34f5df4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move5_3' and @id = 'id_move5_3' and (text() = 'headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor' or . = 'headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor')]</value>
      <webElementGuid>83ffa920-060c-4925-891a-b06acc9b7c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
