<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-danceheadbuttbody-slamtake-do_60a0ca_1_2</name>
   <tag></tag>
   <elementGuidId>a4c8e19c-8c21-4bf2-bab2-adad07016469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move3_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move3_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c46815d-18b1-4138-b23b-6bb268380dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move3_4</value>
      <webElementGuid>fd9c73a9-8fc5-416a-875e-6726dab0e49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move3_4</value>
      <webElementGuid>8657405f-70c1-46f5-bd7d-2440f0cd573f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm</value>
      <webElementGuid>e8158a0f-0a0a-485c-a28c-d96e980b4553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move3_4&quot;)</value>
      <webElementGuid>dbb4db6e-f160-472f-b4a8-836edefdb2c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move3_4']</value>
      <webElementGuid>eeb3e658-9132-4672-b1fc-597cc536d234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[20]/select</value>
      <webElementGuid>49063567-be67-46b9-98ec-e4c61ef267ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[3]/following::select[1]</value>
      <webElementGuid>1cf32bf3-b3f4-4cac-befd-aa129d5c406a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[3]/following::select[2]</value>
      <webElementGuid>df60149b-a536-4bc2-9c2a-8a3218bb812b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 4'])[1]/preceding::select[1]</value>
      <webElementGuid>518268da-6667-4f30-a107-263b21f39a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[4]/preceding::select[2]</value>
      <webElementGuid>555011c0-4529-4839-997d-f07918c7d1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/select</value>
      <webElementGuid>b1f781ba-a490-4cbf-b55a-cbb8481aab31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move3_4' and @id = 'id_move3_4' and (text() = 'swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm' or . = 'swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm')]</value>
      <webElementGuid>3f34c41a-f44a-409d-8dc1-6a3f542e67e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
