<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_gutsno-guardsteadfast</name>
   <tag></tag>
   <elementGuidId>4216679c-7e1a-403c-b11e-4473142d9183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_ability1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_ability1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>07bc52db-6b4b-4207-b506-7e0b898edd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ability1</value>
      <webElementGuid>7a2ab0cc-fc5f-467a-8560-92e6acdec455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_ability1</value>
      <webElementGuid>ea0dfa67-c629-4771-b9d5-b78d4430804d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gutsno-guardsteadfast</value>
      <webElementGuid>405ded0a-034f-4f99-bccc-62b09849fffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_ability1&quot;)</value>
      <webElementGuid>052a7570-4a19-4b2d-ac89-5990af49c038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_ability1']</value>
      <webElementGuid>c3626159-0ecd-4e41-baf6-b3a60f250212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[4]/select</value>
      <webElementGuid>20c172e6-c26e-463e-a3eb-9d2d408d2163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[1]/following::select[1]</value>
      <webElementGuid>50f7d7b5-d9b0-4aa9-a100-6cc9c62256dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 1'])[1]/following::select[2]</value>
      <webElementGuid>198d2b6e-d1b9-4cec-b7b4-b64d5f0e5e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[1]/preceding::select[1]</value>
      <webElementGuid>a08dc2c3-dcb3-4dd0-b92e-54d733b3ce17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[1]/preceding::select[2]</value>
      <webElementGuid>a3665caf-aa9f-4505-852f-73c4f40839dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>7f72cf62-3fb9-44d8-8960-348cf3df4361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ability1' and @id = 'id_ability1' and (text() = 'gutsno-guardsteadfast' or . = 'gutsno-guardsteadfast')]</value>
      <webElementGuid>28902714-8ddb-46a6-880c-46d6572b1cce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
