<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_torrentrain-dish</name>
   <tag></tag>
   <elementGuidId>7db3cb58-c23f-47b7-bd5a-bf9e205a6ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_ability4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_ability4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3cf530fa-b8f8-4493-ab35-4f57dcd12a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ability4</value>
      <webElementGuid>34c3cf9c-0c05-4c58-947c-50d733041367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_ability4</value>
      <webElementGuid>51371db9-1a27-46ea-9425-31760822a73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>torrentrain-dish</value>
      <webElementGuid>2678022f-e7ea-4ab3-8449-391fa34c3760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_ability4&quot;)</value>
      <webElementGuid>0887e4d2-1577-47db-8ddd-8a2d2483d5c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_ability4']</value>
      <webElementGuid>917a585c-0d90-4d53-b5c0-b5a1ddcd5934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[22]/select</value>
      <webElementGuid>786067e3-1a4c-4c2f-a8d2-6a13477d5281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[4]/following::select[1]</value>
      <webElementGuid>4f3d5e95-be67-47e1-8396-fdb47a7c946b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokemon 4'])[1]/following::select[2]</value>
      <webElementGuid>24ccdd82-eb78-4c62-a99f-1e0337fa3658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[4]/preceding::select[1]</value>
      <webElementGuid>a52d42a5-25db-4be2-9846-4238c740513c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[4]/preceding::select[2]</value>
      <webElementGuid>e3fdf105-8a83-4201-bc61-a18ba4467c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/select</value>
      <webElementGuid>db6b79b4-248a-4f21-b365-3d861791d299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ability4' and @id = 'id_ability4' and (text() = 'torrentrain-dish' or . = 'torrentrain-dish')]</value>
      <webElementGuid>0106e9bb-1736-4891-86b5-36f27615e789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
