<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbuttbody-slamtake-downdouble-edg_4ff3fc_1</name>
   <tag></tag>
   <elementGuidId>d3d76543-d2b9-4185-a399-72b54cfbd258</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move5_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move5_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1584bfcb-e6f3-4db2-a02f-446b658e2c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move5_2</value>
      <webElementGuid>c22d361b-58de-4b53-b497-ff5b273cf824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move5_2</value>
      <webElementGuid>54684888-4d7c-46f4-a52d-0127082c684a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor</value>
      <webElementGuid>4c81437f-1a58-4acf-894d-d95313e35c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move5_2&quot;)</value>
      <webElementGuid>19a3dc1c-51b3-479f-a639-fcfc2fc3fddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move5_2']</value>
      <webElementGuid>41925e95-8a29-4062-873b-a9bde9053da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[30]/select</value>
      <webElementGuid>88b30dd9-40aa-44ef-aeae-1e2d9392422b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[5]/following::select[1]</value>
      <webElementGuid>7784c50f-a15c-49a6-8435-6e5c6dcdac50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[5]/following::select[2]</value>
      <webElementGuid>e5270943-62c1-49f9-88e8-7c1db128db00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[5]/preceding::select[1]</value>
      <webElementGuid>15b26a37-e29d-4cd6-983b-ba5905f6a65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[5]/preceding::select[2]</value>
      <webElementGuid>2c0722eb-12d7-471f-96ee-03ee5472e30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/select</value>
      <webElementGuid>761623b7-ee58-4ac4-b8cd-e88a81f34787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move5_2' and @id = 'id_move5_2' and (text() = 'headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor' or . = 'headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor')]</value>
      <webElementGuid>97f366a3-46cb-47ce-9969-87b2f08d6fd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
