<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbuttbody-slamtake-downdouble-edg_4ff3fc</name>
   <tag></tag>
   <elementGuidId>434a9ebc-b649-42eb-8521-de29cdfdab86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move5_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move5_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>24c9e0ce-a1d9-448a-8062-85dbae23522e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move5_1</value>
      <webElementGuid>ccf476a5-0e3b-461d-a19c-342c8c691b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move5_1</value>
      <webElementGuid>a2707385-d90c-436b-bfe7-9903a7804fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor</value>
      <webElementGuid>87d12618-e40d-4d99-ad94-f42b3c82fbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move5_1&quot;)</value>
      <webElementGuid>0394af59-e75a-445a-8e61-e05216f62976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move5_1']</value>
      <webElementGuid>0b28aa2f-755b-4f95-8789-53082855e9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[29]/select</value>
      <webElementGuid>dcb60f9e-12dc-4011-8337-035eca721df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[5]/following::select[1]</value>
      <webElementGuid>fea98690-47c6-4de2-ba3d-20ec372256ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ability'])[5]/following::select[2]</value>
      <webElementGuid>ea3175b6-72d2-48fc-bd5f-e226e4b2b02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[5]/preceding::select[1]</value>
      <webElementGuid>cc981aa0-2812-453a-944e-9b528eb4f4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[5]/preceding::select[2]</value>
      <webElementGuid>e3f63321-b1bb-44e6-baf4-89b6592f1fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/select</value>
      <webElementGuid>9d9ea84e-02ad-41a9-994f-59be99b9e929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move5_1' and @id = 'id_move5_1' and (text() = 'headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor' or . = 'headbuttbody-slamtake-downdouble-edgetoxicmimicdouble-teamrestsubstitutesnorecurseprotectoutrageendureswaggerattractsleep-talkreturnfrustrationhidden-powerfacadesecret-powerweather-ballnatural-giftcaptivateroundconfidetera-blasthyper-beamscary-facegiga-impactleersmokescreenswiftdragon-breathdragon-dancedragon-pulsebreaking-swipetwisterhurricanescale-shotwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwaterfallbubbleflailicy-windrain-dancewhirlpoolhailyawndivemuddy-waterwater-pulsebrinescaldliquidationflip-turnwave-crashchilling-watersignal-beamflash-cannonagilityfocus-energylaser-focusdisablequashsplashbounceclear-smogiron-headaurora-beamsnowscapedraco-meteor')]</value>
      <webElementGuid>490d15f2-7713-4fa3-90cf-1c2fd5ae68b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
