<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-dancecutheadbuttbody-slamtake_ab05fc_1_2_3</name>
   <tag></tag>
   <elementGuidId>1fb7ab47-1745-4fb3-a2fc-1a2f28468c6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move6_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move6_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed73f8de-0387-4bcf-8721-3760c9da3623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move6_4</value>
      <webElementGuid>bda92be4-2039-4030-84e1-263c5f110e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move6_4</value>
      <webElementGuid>69185210-d452-47db-9063-42efd4f9a56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut</value>
      <webElementGuid>fcd42cc3-7b7c-40e7-a2e1-2d085c6d0353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move6_4&quot;)</value>
      <webElementGuid>05a1ab41-b455-4943-b76a-9eb665acbb5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move6_4']</value>
      <webElementGuid>a6ae62a4-e27c-4e80-80b2-12755c322dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[38]/select</value>
      <webElementGuid>f639b989-a67e-42b1-bd26-c930f15c149f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[6]/following::select[1]</value>
      <webElementGuid>ecef93e4-ea2c-4869-a55c-cd9af40c7085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[6]/following::select[2]</value>
      <webElementGuid>19bd8302-429e-4b10-8d37-d2432a02c1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>204597f6-81da-4e97-8db5-f7b9183f4dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created by Taj Smith 2024'])[1]/preceding::select[1]</value>
      <webElementGuid>5880fe2f-7759-498a-8466-b278bffe4392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[38]/select</value>
      <webElementGuid>b4ac4050-5e67-4539-8a38-01952eb76e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move6_4' and @id = 'id_move6_4' and (text() = 'swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut' or . = 'swords-dancecutheadbuttbody-slamtake-downdouble-edgegrowlstrengthsolar-beamtoxicmimicdouble-teamrestsubstitutesnorecurseprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handknock-offsecret-powernatural-giftcaptivateroundechoed-voicework-upconfidetera-blastroarhyper-beamearthquakepoison-jabgiga-impactrock-climbbulldozemega-punchfire-punchthunder-punchscratchmega-kickemberflamethrowercounterseismic-tossfire-spindigfire-blastswiftrock-slideslashdynamic-punchheat-wavewill-o-wispfocus-punchbrick-breakoverheatrock-tombaerial-aceflingflare-blitzfocus-blastshadow-clawhone-clawsflame-chargeincinerateacrobaticsfire-pledgepower-up-punchtemper-flareblaze-kickblast-burndefogheat-crashscorching-sandsaura-spherethiefbaton-passu-turnpeckagilityfocus-energyassurancelaser-focussand-attackquick-attackmirror-movedetectuproarfeather-dancebrave-birdreversalrevengelast-resortdouble-kickfeintupper-handlow-kickcrush-clawnight-slashstone-edgesuperpowerrole-playbouncevacuum-wavelow-sweepbulk-upclose-combatdual-chopcoachinghigh-jump-kicksky-uppercut')]</value>
      <webElementGuid>f5aa8a77-ca8a-4493-88b8-e3fb0d0df1b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
