<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_headbutttacklebody-slamtake-downdoub_18edfb_1</name>
   <tag></tag>
   <elementGuidId>8a0079df-1f96-4015-8e0e-4a667871b396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move4_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move4_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>36efaf27-c6bd-44fd-a27e-182ccfccbf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move4_2</value>
      <webElementGuid>df755f7a-6b03-4515-a66d-4bf1c95ed8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move4_2</value>
      <webElementGuid>4ca8b418-2256-4034-a1e2-381e9f905676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press</value>
      <webElementGuid>a90a616e-59a6-4990-9afe-394af531e2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move4_2&quot;)</value>
      <webElementGuid>3dcd6c4f-f756-4e93-970d-f3c03dc3714f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move4_2']</value>
      <webElementGuid>75b15069-071c-46c3-a4b4-5a92d123772c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[24]/select</value>
      <webElementGuid>a2dfe286-521e-4d57-a8ea-a46f3f5905cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[4]/following::select[1]</value>
      <webElementGuid>1f56d45f-f2c8-4766-ab61-d3c0861b1428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[4]/following::select[2]</value>
      <webElementGuid>6a9909c5-5d97-41a4-8ef7-c221618be9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[4]/preceding::select[1]</value>
      <webElementGuid>0a4537bf-38d0-474f-8993-4f2c0f86e9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[4]/preceding::select[2]</value>
      <webElementGuid>aa3a9b98-8ef9-4174-8105-35f9170ddd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/select</value>
      <webElementGuid>9f3921d1-1162-419c-8a38-0d3e41368097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move4_2' and @id = 'id_move4_2' and (text() = 'headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press' or . = 'headbutttacklebody-slamtake-downdouble-edgestrengthtoxicragemimicdouble-teamdefense-curlreflectbideskull-bashrestsubstitutesnorecurseprotectmud-slapoutrageendurefalse-swipeswaggerattractsleep-talkreturnfrustrationhidden-powerrock-smashfacadehelping-handsecret-powerweather-ballnatural-giftcaptivateroundwork-upconfidetera-blastroarhyper-beamearthquakescary-facegiga-impactrock-climbbulldozeterrain-pulsemega-punchmega-kickbitesubmissioncounterseismic-tossdigrock-slidedynamic-punchiron-tailcrunchfocus-punchbrick-breakrock-tombflingdragon-pulsefocus-blastdragon-tailpower-up-punchfissureice-punchtail-whipmistwater-gunhydro-pumpsurfice-beamblizzardbubble-beamwithdrawhazewaterfallbubbleflailicy-windrolloutrapid-spinrain-dancemirror-coatwhirlpoolfake-outhailyawndivewater-spoutmuddy-wateriron-defensemud-shotwater-pulsegyro-ballbrineaqua-ringaura-sphereaqua-tailzen-headbuttaqua-jetscaldshell-smashwater-pledgeliquidationlife-dewflip-turnwave-crashice-spinnerchilling-waterhydro-cannonsignal-beamdark-pulseavalancheflash-cannonsmack-downbody-press')]</value>
      <webElementGuid>59efe5b8-440a-4f8e-945c-fe9f92bea062</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
