<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_swords-danceheadbuttbody-slamtake-do_60a0ca</name>
   <tag></tag>
   <elementGuidId>72fd086a-8c20-4b36-939f-200c5068db0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_move3_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_move3_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4e2ec25-b07f-4566-9e87-90e976a2e322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move3_2</value>
      <webElementGuid>d6ac4f6d-d04d-4f05-b109-43e966ee43ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_move3_2</value>
      <webElementGuid>d90d6069-1983-4f01-9e64-869608fde4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm</value>
      <webElementGuid>da7cbf73-80cd-4039-8f33-3d6f82257427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_move3_2&quot;)</value>
      <webElementGuid>c3a7a94a-8151-4a62-83c1-c3c3c5db574c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_move3_2']</value>
      <webElementGuid>1115e7d6-1991-43e4-a036-78ffd4b7c15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/form/div[18]/select</value>
      <webElementGuid>9339de69-0ec0-498d-879c-f91627b30965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 2'])[3]/following::select[1]</value>
      <webElementGuid>8184f46b-2c92-4b75-b554-6fc727101e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 1'])[3]/following::select[2]</value>
      <webElementGuid>50ab4465-317f-4c7d-bf2e-76f6c3e158e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 3'])[3]/preceding::select[1]</value>
      <webElementGuid>9db351fd-948f-45e2-a0a0-d9f0c30c2f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move 4'])[3]/preceding::select[2]</value>
      <webElementGuid>b8fe1032-6576-42f5-bb6f-8b5987e48282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/select</value>
      <webElementGuid>960e9ba0-e3b9-4da6-8603-2a90b7bbb9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'move3_2' and @id = 'id_move3_2' and (text() = 'swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm' or . = 'swords-danceheadbuttbody-slamtake-downstrengthtoxicdouble-teamrestsubstitutesnoreprotectmud-slapendureswaggerfury-cutterattractsleep-talkreturnfrustrationhidden-powersunny-dayrock-smashfacadehelping-handsecret-powernatural-giftcaptivateroundwork-upconfidetera-blasttrailblazeroarhyper-beamearthquakescary-facepoison-jabgiga-impactrock-climbbulldozeterrain-pulsemega-punchthunder-punchmega-kickcounterdigswiftrock-slideiron-tailmetal-clawcrunchfocus-punchbrick-breakrock-tombaerial-aceflingdragon-pulsefocus-blastshadow-clawhone-clawspower-up-punchblaze-kickice-punchforesightrain-danceiron-defensewater-pulseaura-spherezen-headbuttlife-dewdark-pulseflash-cannonpsychicpsych-upshadow-ballagilityfocus-energypaybacklaser-focusquick-attackdetectscreechreversalrevengeme-firstretaliatefinal-gambitcalm-mindfeintmagnet-risenasty-plotupper-handlow-kickstone-edgemetronomerole-playmeteor-mashcopycatdrain-punchheal-pulsequick-guardvacuum-wavelow-sweepbulk-upclose-combatdual-chopextreme-speedcoachingmetal-soundsteel-beambone-rushforce-palm')]</value>
      <webElementGuid>f1069df5-0a49-4687-9566-8d8de2ea7580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
