<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Special Attack 85</name>
   <tag></tag>
   <elementGuidId>c59aaf37-76b3-4b5a-90e8-e153ff2e1271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrap']/div/ul[2]/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0a619634-d5a7-4b28-9100-e4db55ea711e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Special Attack: 85</value>
      <webElementGuid>2d3d5325-2f65-4610-8be5-ebbcecad7fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrap&quot;)/div[@class=&quot;mycardpoison&quot;]/ul[2]/li[4]</value>
      <webElementGuid>a14b3cd2-d930-46a8-8226-dd90faafd53c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/div/ul[2]/li[4]</value>
      <webElementGuid>28d506fb-6b6a-4558-ad56-1b4e59d2acfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Defense:'])[1]/following::li[1]</value>
      <webElementGuid>cdf99251-ece6-41b2-b4bd-a2f0548c4034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attack:'])[1]/following::li[2]</value>
      <webElementGuid>16503529-a957-423e-8b72-0c17d469240c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Defense:'])[1]/preceding::li[1]</value>
      <webElementGuid>41a9cccd-0525-4adc-ae7f-c118e7186b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='85']/parent::*</value>
      <webElementGuid>b199a027-a0b6-47d3-bfaf-1cbd20a57d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>1d1142fe-bb07-4bd2-a3ee-9b8823569c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Special Attack: 85' or . = 'Special Attack: 85')]</value>
      <webElementGuid>2e1d0feb-c682-4fd1-9a06-4054eada526a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
