<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min damage_min_damage</name>
   <tag></tag>
   <elementGuidId>8e8aab46-cb37-4182-b6ce-d23f05bd5698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_min_damage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_min_damage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9df4cbec-66f9-4230-900b-62aa27629f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b7534401-3162-4ac3-988d-5bfe1e48e5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>min_damage</value>
      <webElementGuid>544cd8dd-814d-4379-aa28-79af714932f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_min_damage</value>
      <webElementGuid>26f58013-4c3c-4ea4-a5b2-fa133c486907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_min_damage&quot;)</value>
      <webElementGuid>4aeae728-78eb-4a70-8239-37acf3fa1045</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_min_damage']</value>
      <webElementGuid>7f06f3cc-330a-4567-b6dc-2a7afc617a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movesinnerfilterform']/form/p[3]/input</value>
      <webElementGuid>58ee0b24-a555-4c78-95f9-16e268ca982f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d212c992-45f6-4908-97f7-264b2cd83094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'min_damage' and @id = 'id_min_damage']</value>
      <webElementGuid>82f32680-5e29-4f94-9870-0dd50275bf22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
