<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_drain-punch</name>
   <tag></tag>
   <elementGuidId>85cbefcd-d21a-455a-b9c0-2ec8d0f86bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrap']/div/ul[3]/div[106]/a/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>51df9cfd-ade3-4954-8b9c-8c2d3324ff7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>drain-punch</value>
      <webElementGuid>98d313e6-5010-43d4-b1d1-2a54cac1a160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrap&quot;)/div[@class=&quot;mycardfighting&quot;]/ul[3]/div[@class=&quot;fighting&quot;]/a[1]/li[1]</value>
      <webElementGuid>70a87f25-7141-4743-bf2a-a9bb8e8d722c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/div/ul[3]/div[106]/a/li</value>
      <webElementGuid>7c314908-a753-4f0e-81b2-2ed4748c4aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='role-play'])[1]/following::li[1]</value>
      <webElementGuid>ba508eba-a2c8-4b17-a710-b10a43ac8c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='metronome'])[1]/following::li[2]</value>
      <webElementGuid>3fe74908-3ff6-400a-8a9b-67c3b968779e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='punishment'])[1]/preceding::li[1]</value>
      <webElementGuid>fd51526f-865f-4f37-9e2b-b99a807f5ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cross-chop'])[1]/preceding::li[2]</value>
      <webElementGuid>35591fb0-aa3c-449b-8764-87af133fd08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='drain-punch']/parent::*</value>
      <webElementGuid>a3537f8b-58cd-4c76-a471-1d5c0a99d296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[106]/a/li</value>
      <webElementGuid>92f24975-4186-4e8f-9c6e-e2b177204756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'drain-punch' or . = 'drain-punch')]</value>
      <webElementGuid>12b4e5bc-3427-4200-945b-38d9ed199d35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
