<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TEAMS</name>
   <tag></tag>
   <elementGuidId>58518d0f-7a44-49e8-b00c-b1336ad64c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-container']/nav/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>75741a8c-7609-4474-9414-3a3854e4bd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/teams/</value>
      <webElementGuid>10921b01-4a9f-42cf-834e-060dcaeb31ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEAMS</value>
      <webElementGuid>8e793e94-ce5a-4431-820e-a562c1384dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-container&quot;)/nav[@class=&quot;topnav&quot;]/a[4]</value>
      <webElementGuid>c5e6f11c-f072-4847-8b14-ec8dd2ab1b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-container']/nav/a[4]</value>
      <webElementGuid>68eb14cb-dcb1-4c41-9766-854f99996f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TEAMS')]</value>
      <webElementGuid>f81e6356-220f-41c1-bb6d-b764279accef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOVES'])[1]/following::a[1]</value>
      <webElementGuid>07bc3fd8-8bdb-4d4e-b76d-10ce885b236f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POKEMON'])[1]/following::a[2]</value>
      <webElementGuid>d5a8f04d-48ae-40c4-9909-0e41d5de7b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMMUNITY'])[1]/preceding::a[1]</value>
      <webElementGuid>3d48cc88-5b42-462e-8e8d-7465edfbac3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROFILE'])[1]/preceding::a[2]</value>
      <webElementGuid>48cb1725-70c2-4f90-b202-70b07d5700a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEAMS']/parent::*</value>
      <webElementGuid>cb3bf0d0-b2bb-4e26-9d67-cdc755dfb65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/teams/')]</value>
      <webElementGuid>2657d01d-1d58-421b-b47d-ded5e1032d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>0434bc37-1637-4484-9df5-6df9e8a90a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/teams/' and (text() = 'TEAMS' or . = 'TEAMS')]</value>
      <webElementGuid>9ba9b70c-165c-42d2-b191-d7e2ca3ff2ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
