<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MOVES</name>
   <tag></tag>
   <elementGuidId>e3eda07a-8b2b-4ef3-976e-fffbe701a48a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-container']/nav/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6496ee82-40c2-40bc-ac00-1dd9229ff5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/moves/</value>
      <webElementGuid>7c14af3f-3a6b-4819-b563-58daf884cafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MOVES</value>
      <webElementGuid>9d87be8b-e3c0-418f-862f-1e0c2a93fcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-container&quot;)/nav[@class=&quot;topnav&quot;]/a[3]</value>
      <webElementGuid>0dd258ee-83a5-4617-bae1-588446f0934f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-container']/nav/a[3]</value>
      <webElementGuid>ecb18701-d496-44e9-b57a-d16df650904e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MOVES')]</value>
      <webElementGuid>3f7f27ff-90aa-425e-a51f-c2592cbd6153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POKEMON'])[1]/following::a[1]</value>
      <webElementGuid>6ed640ec-a2e9-4476-a9ee-e08078216599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/following::a[2]</value>
      <webElementGuid>67040dfa-f67c-44a0-a91d-6905dd81c0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEAMS'])[1]/preceding::a[1]</value>
      <webElementGuid>7dfbb0af-ff7a-4fae-a903-b943adb45fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMMUNITY'])[1]/preceding::a[2]</value>
      <webElementGuid>53e1cd27-0979-49eb-b05a-0b7328e645d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MOVES']/parent::*</value>
      <webElementGuid>473d94d5-a754-4fc4-a025-f2cb5cc37c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/moves/')]</value>
      <webElementGuid>584a8f14-1b26-4bf2-9e06-dd5539464d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>22f679f0-7c4b-4448-b76c-c15924a471fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/moves/' and (text() = 'MOVES' or . = 'MOVES')]</value>
      <webElementGuid>0ccb919e-9ef8-477f-ad88-714d907aae13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
