<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply Filters</name>
   <tag></tag>
   <elementGuidId>addbf769-3f7a-4fd3-bc0e-a3f86eda3ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_form_submit_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='filter_form_submit_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc5dd9c4-1a7e-4857-b602-17cd9eefa4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b6c12205-1e82-46cb-909e-4174a40b3ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_form_submit_button</value>
      <webElementGuid>cd00357e-f231-44c0-9ef1-d7ef9fccff91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply Filters</value>
      <webElementGuid>eb5896f8-b515-4002-a611-c81a4b367ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_form_submit_button&quot;)</value>
      <webElementGuid>9dc337ff-7d83-452f-8e30-4dcad4099aab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='filter_form_submit_button']</value>
      <webElementGuid>fc05458a-052a-42c5-a3ed-7f57ea1f6121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerfilterform']/button</value>
      <webElementGuid>94618c9c-9aed-4a03-a359-be0fc700e4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/following::button[1]</value>
      <webElementGuid>54c5e3be-413b-43da-bdd8-dcaaac0058db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::button[1]</value>
      <webElementGuid>79e34f62-3986-49c2-a1a0-afafd75de105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::button[1]</value>
      <webElementGuid>96df83b4-ef01-4cfa-9b9a-3c0cfc3c9334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#1 | bulbasaur | grass, poison'])[1]/preceding::button[2]</value>
      <webElementGuid>3ddf9654-cdd9-4381-92f9-76c9d80b256f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply Filters']/parent::*</value>
      <webElementGuid>039611a4-9189-4651-95c0-00bb9f503298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>69c1380e-5c11-47d4-95e3-4c34467a2f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'filter_form_submit_button' and (text() = 'Apply Filters' or . = 'Apply Filters')]</value>
      <webElementGuid>9c5fa710-a395-4715-a33c-249981ec9b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
