<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_poke_name</name>
   <tag></tag>
   <elementGuidId>2102181b-66dd-40b0-8fe0-f2c5fc4d5563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='poke_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;poke_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>727668a1-5509-4ac3-85b3-aa64a5665d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1838062d-c999-4f86-b89d-4109bcdcd147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>poke_name</value>
      <webElementGuid>1f76ada1-c505-4a4e-ba4f-85f0f8a252c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by name</value>
      <webElementGuid>68fd4cf2-5299-47c7-b189-cba502961a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wholefilterform&quot;)/div[@id=&quot;innerfilterform&quot;]/div[@id=&quot;innerfilterform&quot;]/input[2]</value>
      <webElementGuid>2dc05315-0b4a-4024-92f7-b8cc1dd237a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='poke_name']</value>
      <webElementGuid>75558509-2843-4772-b14b-c95271257419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerfilterform']/input[2]</value>
      <webElementGuid>d0a2ccef-0b00-404f-aef2-85f11d404ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>ac256c99-ac17-4cba-899f-958f97ebdd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'poke_name' and @placeholder = 'Search by name']</value>
      <webElementGuid>70f6a6d4-38e9-479c-947a-c25afeeaa60d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
