<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min DEFENSE_min_defense</name>
   <tag></tag>
   <elementGuidId>5db3f364-7756-4c05-bf00-7ef9bde3f053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='min_defense']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;min_defense&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cfcfedc-ab73-4f45-b585-db286bbe8e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>be3cf0b0-9c1c-41de-81d6-194ecc81be25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>min_defense</value>
      <webElementGuid>86a3bc31-00da-45d0-b6cd-3c3ef7e9ceac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DEFENSE</value>
      <webElementGuid>7f2195cb-cf18-4f29-a1ae-0eb05efee0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wholefilterform&quot;)/div[@id=&quot;innerfilterform&quot;]/div[@id=&quot;innerfilterform&quot;]/input[5]</value>
      <webElementGuid>83f9fec6-836a-47f5-bd67-9864706adba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='min_defense']</value>
      <webElementGuid>d786c915-a1e4-4016-9e07-86534fa8c0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerfilterform']/input[5]</value>
      <webElementGuid>dd973bce-accd-4777-aaf1-46d40c68f666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>fd135623-18f0-4f39-b8b6-b1d664bdee15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'min_defense' and @placeholder = 'DEFENSE']</value>
      <webElementGuid>c5c571fa-7229-45f4-820d-484efd983e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
