<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min SP. ATTACK_min_special_attack</name>
   <tag></tag>
   <elementGuidId>69f01d95-253a-4dac-bae1-4b243698becd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='min_special_attack']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;min_special_attack&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95aa9bb3-6987-47f8-b6b1-213cba3150ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>83bef0e8-760f-4540-997b-8510ba8f18f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>min_special_attack</value>
      <webElementGuid>32e35340-3228-443d-a221-5f30361e09dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SP. ATTACK</value>
      <webElementGuid>acdc110b-3fe2-4be2-a4c9-c7496abe61c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wholefilterform&quot;)/div[@id=&quot;innerfilterform&quot;]/div[@id=&quot;innerfilterform&quot;]/input[6]</value>
      <webElementGuid>19479d7c-284e-4383-89b5-10c7d8c13ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='min_special_attack']</value>
      <webElementGuid>bdc6406f-687b-47fb-b314-3a26a938590f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerfilterform']/input[6]</value>
      <webElementGuid>69f3f773-63ad-4440-a03b-70e1979a3772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>b442333d-cf3f-4429-a135-53fd63ab7bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'min_special_attack' and @placeholder = 'SP. ATTACK']</value>
      <webElementGuid>e5459e65-d32c-4468-98e3-e08a0f09f945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
