<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min SPEED_min_speed</name>
   <tag></tag>
   <elementGuidId>a3c4349b-d586-414a-87e6-ba500bab083e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='min_speed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;min_speed&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b537c8fb-c666-4b23-a659-bf35490a2d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c627bb2e-57ec-4779-8fcf-209db308a286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>min_speed</value>
      <webElementGuid>1aebf6e0-eab8-4d23-a4a4-a314b9d8347b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SPEED</value>
      <webElementGuid>2bb7eed0-4c27-44bf-8e06-9b6ccba0a6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wholefilterform&quot;)/div[@id=&quot;innerfilterform&quot;]/div[@id=&quot;innerfilterform&quot;]/input[8]</value>
      <webElementGuid>78e625ca-1d1a-43df-9523-acdf1c836c74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='min_speed']</value>
      <webElementGuid>13e5fceb-14ac-4d76-8d8e-f4527ba45863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerfilterform']/input[8]</value>
      <webElementGuid>0f778aea-6a55-485a-acde-1de3918e7306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>d7a382d7-30c7-411d-b1b5-c9a021870ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'min_speed' and @placeholder = 'SPEED']</value>
      <webElementGuid>59dd0b53-14b5-4e17-bd50-c66ebd2d775b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
