<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pokedex_pokedex_number</name>
   <tag></tag>
   <elementGuidId>ff7da6e8-0fd5-46e5-b853-e53e80657c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pokedex_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pokedex_number&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bfd7da3-41a4-46e4-ac48-95797c6682e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>bd674125-bdfc-4fff-a510-379ee438a641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pokedex_number</value>
      <webElementGuid>25073352-4fae-4327-8d6c-093053d96caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by pokedex #</value>
      <webElementGuid>072170d1-ad18-4659-8009-e79e05be6632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1025</value>
      <webElementGuid>eec35909-3ad4-4bd7-aefd-bdb092390ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wholefilterform&quot;)/div[@id=&quot;innerfilterform&quot;]/div[@id=&quot;innerfilterform&quot;]/input[1]</value>
      <webElementGuid>4a04f35f-6068-4ee6-a505-d903b16bc552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pokedex_number']</value>
      <webElementGuid>fb767e22-c80e-438b-a8ef-0b1057d9a8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerfilterform']/input</value>
      <webElementGuid>fd2c2f56-e64c-4181-9b42-5f5968f1f4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>55c02aec-d428-4cc7-9b40-2a7698706b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pokedex_number' and @placeholder = 'Search by pokedex #']</value>
      <webElementGuid>87161350-e3ee-44af-8722-3384064c5d6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
