<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_460  abomasnow  grass, ice</name>
   <tag></tag>
   <elementGuidId>299246be-d35c-4adf-bd4b-18dd97e8d6dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrap']/div/div/ul/a/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d3b049d5-b84f-42b9-b841-d975f987f74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#460 | abomasnow | grass, ice</value>
      <webElementGuid>762b13bc-e4ae-4e7b-8225-80656b78291c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrap&quot;)/div[@class=&quot;mycardall&quot;]/div[@class=&quot;grass&quot;]/ul[1]/a[1]/li[1]</value>
      <webElementGuid>90f58e23-8964-49f3-b4af-9a370f785c4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/div/div/ul/a/li</value>
      <webElementGuid>c2b3256e-ecae-497a-9d93-ac3746ec411c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::li[1]</value>
      <webElementGuid>e0da354a-9a55-442f-a65f-557e85ad9428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Filters'])[1]/following::li[1]</value>
      <webElementGuid>6d44008d-36f0-44c7-9650-e313e216c112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#63 | abra | psychic'])[1]/preceding::li[1]</value>
      <webElementGuid>53dbadf4-464e-4e5b-84b1-1d5eb4eba155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#359 | absol | dark'])[1]/preceding::li[2]</value>
      <webElementGuid>e116f487-3a04-4f40-9fc8-e401f05cc607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#460 | abomasnow | grass, ice']/parent::*</value>
      <webElementGuid>4422e518-bdcd-4b9f-a316-5cf2e1589237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>420f96ca-2958-447f-ae64-6de0c3ff5666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '#460 | abomasnow | grass, ice' or . = '#460 | abomasnow | grass, ice')]</value>
      <webElementGuid>532512e5-275f-4ae3-966f-af9cd2540618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
