<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_697  tyrantrum  rock, dragon</name>
   <tag></tag>
   <elementGuidId>ac132dcb-e0c8-40d5-a82a-d1eaa2676b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrap']/div/div[2]/ul/a/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f70ae267-8d73-4f67-9250-b3baceadc65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#697 | tyrantrum | rock, dragon</value>
      <webElementGuid>c712ef92-36e5-482a-b93e-dfe3a67e8c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrap&quot;)/div[@class=&quot;mycardall&quot;]/div[@class=&quot;rock&quot;]/ul[1]/a[1]/li[1]</value>
      <webElementGuid>d0c8ebc8-5a17-4169-8b30-cb27ae1de2f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrap']/div/div[2]/ul/a/li</value>
      <webElementGuid>acf2f5a4-90a8-44b0-8032-11ed49105ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#696 | tyrunt | rock, dragon'])[1]/following::li[1]</value>
      <webElementGuid>2f8ad17b-455d-4497-bb4b-b7f55f41e3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::li[2]</value>
      <webElementGuid>62f58fc0-6ca2-41da-b214-e6b4488c6fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#734 | yungoos | normal'])[1]/preceding::li[1]</value>
      <webElementGuid>9e0189f4-b60b-4756-af80-7963b3acd31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#735 | gumshoos | normal'])[1]/preceding::li[2]</value>
      <webElementGuid>693aa7bc-ca04-4107-9c55-6e44f450960b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#697 | tyrantrum | rock, dragon']/parent::*</value>
      <webElementGuid>bba6344e-0301-4082-a48e-6563c5fb5273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/a/li</value>
      <webElementGuid>a7b3923e-0b0d-4ab6-9717-4bb3bfa3e0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '#697 | tyrantrum | rock, dragon' or . = '#697 | tyrantrum | rock, dragon')]</value>
      <webElementGuid>79b71358-1cb0-4212-9e72-ebffaa87622f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
