<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_10            25            50      _ceab21</name>
   <tag></tag>
   <elementGuidId>69dd80c2-2865-4e16-81f5-98f01b12e9d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#per_page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='per_page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b09e5639-a4a5-423e-bf3f-6db9fb34915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>per_page</value>
      <webElementGuid>5dc8d68e-4845-4b68-85ea-22143da57b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>per_page</value>
      <webElementGuid>b33c01ae-3755-4247-bb79-49baca5bf547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            10
            25
            50
            100
        </value>
      <webElementGuid>1d0c5b6d-cb61-4937-a1cf-0e23572fe0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;per_page&quot;)</value>
      <webElementGuid>486ee5a7-c954-4781-9850-302cda3f49fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='per_page']</value>
      <webElementGuid>12c359b3-c5ee-4808-aedd-544f39a11ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerfilterform']/select[5]</value>
      <webElementGuid>1f18ff82-f3ef-4a88-85fa-7bc9c09c1321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/following::select[1]</value>
      <webElementGuid>5d9a4e87-3aa3-446c-b328-b1792b12be71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::select[2]</value>
      <webElementGuid>1734c1d4-0f49-41c1-8956-c05800f249d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Filters'])[1]/preceding::select[1]</value>
      <webElementGuid>3f77a5c0-e3d7-443a-8485-93962fb6d79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::select[1]</value>
      <webElementGuid>8a68130d-d94e-4253-8e18-1a818c88fab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[5]</value>
      <webElementGuid>d9f5438d-d755-4596-bbab-ef33441dca54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'per_page' and @id = 'per_page' and (text() = '
            10
            25
            50
            100
        ' or . = '
            10
            25
            50
            100
        ')]</value>
      <webElementGuid>43a37cc5-0a96-43ab-8f3b-e25f99f0f49d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
