<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pokedex             Name</name>
   <tag></tag>
   <elementGuidId>c55224d9-0530-4a92-b5da-0ea598208dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sort_by</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sort_by']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>745d9e2b-975d-40c0-88c8-e877b674d854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sort_by</value>
      <webElementGuid>435a456a-83d3-4ffd-941d-3a069be5e7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sort_by</value>
      <webElementGuid>53eb6f02-2d01-442b-83a1-7237e7c19458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Pokedex #
            Name
        </value>
      <webElementGuid>8ab791c1-947c-4735-9d29-c1e83f48125a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sort_by&quot;)</value>
      <webElementGuid>a6b5c0bd-c4b1-4a79-a18a-edacc1a6253c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sort_by']</value>
      <webElementGuid>d58e645f-9641-48b9-8075-6cb5543ec380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerfilterform']/select[4]</value>
      <webElementGuid>758ef30c-f8b4-49bf-99ea-f8fd3486ece8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::select[1]</value>
      <webElementGuid>04e2039a-b986-4662-9f1a-09124f603d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Min SPEED:'])[1]/following::select[1]</value>
      <webElementGuid>858e4bfa-3326-4900-aca4-1b993ce22da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/preceding::select[1]</value>
      <webElementGuid>8dad27c0-6bd0-4974-925f-124d57b98959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Filters'])[1]/preceding::select[2]</value>
      <webElementGuid>828c12a7-1cbc-4c59-a4d0-73abba8811ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[4]</value>
      <webElementGuid>d0ac696f-e545-46c4-83bf-a6c8d6e44f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sort_by' and @id = 'sort_by' and (text() = '
            Pokedex #
            Name
        ' or . = '
            Pokedex #
            Name
        ')]</value>
      <webElementGuid>06fc7bd3-baed-4be5-9360-ebaf66d2a2c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
